language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

script: bin/idephix.phar buildTravis

after_script:
  - vendor/bin/test-reporter

branches:
  only:
    - master

addons:
  code_climate:
    repo_token: d78a2bee0da040438a789f86c200b705caaa43eea2358a2610cef18e3960f145
